name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Close PRs that contain content for services that have been migrated out of the azure-docs-pr repository.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/aks/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/defender-for-cloud/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/attestation/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/confidential-ledger/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/dedicated-hsm/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/key-vault/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/payment-hsm/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/postgresql/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/cosmos-db/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/dms/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/mariadb/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/mysql/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/managed-instance-apache-cassandra/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/virtual-machines/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/virtual-machines-scale-sets/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/container-instances/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/service-fabric/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/machine-learning/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/ai-studio/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/ai-services/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/genomics/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/open-datasets/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/search/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-monitor/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/advisor/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/chaos-studio/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/service-health/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-arc/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-linux/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/azure-portal/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/copilot/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/lighthouse/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/quotas/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/container-registry/*
              - filesMatchPattern:
                  matchAny: true
                  pattern: articles/kubernetes-fleet/*
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - You tried to add content to a folder path that has been removed from this repository. Your pull request will be automatically closed. Submit your changes to the updated repository, which can be identified by clicking the Edit this Document link at the top of any published article for that product or service.
          - closePullRequest

      - description: Alert authors to edits in the /articles/reliability folder.
        if:
          # If a PR in the articles/reliability folder was opened or had the ready-to-merge label added, and the PR author isn't Anastasia or John...
          - payloadType: Pull_Request
          - or:
              - isAction:
                  action: Opened
              - labelAdded:
                  label: ready-to-merge
          - filesMatchPattern:
              matchAny: true
              pattern: articles/reliability/*
          - not:
              or:
                - isActivitySender:
                    user: anaharris-ms
                - isActivitySender:
                    user: johndowns
        then:
          # Add the needs-human-review label, remove the ready-to-merge label (if necessary), mention Anastasia and John, and add a reply asking the PR author not to sign off on the PR.
          - mentionUsers:
              mentionees:
                - anaharris-ms
                - johndowns
              replyTemplate: >-
                Tagging authors for this folder: ${mentionees}
          - addReply:
              reply: >-
                @${issueAuthor} - Please do NOT sign off on this pull request. The article author will sign off for you.
          - addLabel:
              label: needs-human-review
          - removeLabel:
              label: ready-to-merge

