name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
resource: repository

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Close PRs that contain content for services that have been migrated out of the azure-docs-pr repository.
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - or:
              - filesMatchPattern:
                  pattern: articles/aks/*
              - includesModifiedFiles:
                  files:
                    - articles/defender-for-cloud/*
              - includesModifiedFiles:
                  files: 
                    - articles/attestation/*
              - includesModifiedFiles:
                  files: 
                    - articles/confidential-ledger/*
              - includesModifiedFiles:
                  files: 
                    - articles/dedicated-hsm/*
              - includesModifiedFiles:
                  files:
                    - articles/key-vault/*
              - includesModifiedFiles:
                  files: 
                    - articles/payment-hsm/*
              - includesModifiedFiles:
                  files: 
                    - articles/postgresql/*
              - includesModifiedFiles:
                  files: 
                    - articles/cosmos-db/*
              - includesModifiedFiles:
                  files: 
                    - articles/dms/*
              - includesModifiedFiles:
                  files: 
                    - articles/mariadb/*
              - includesModifiedFiles:
                  files: 
                    - articles/mysql/*
              - includesModifiedFiles:
                  files:   
                    - articles/managed-instance-apache-cassandra/*
              - includesModifiedFiles:
                  files:   
                    - articles/virtual-machines/*
              - includesModifiedFiles:
                  files:   
                    - articles/virtual-machines-scale-sets/*
              - includesModifiedFiles:
                  files:   
                    - articles/container-instances/*
              - includesModifiedFiles:
                  files:   
                    - articles/service-fabric/*
              - includesModifiedFiles:
                  files:   
                    - articles/machine-learning/*
              - includesModifiedFiles:
                  files:   
                    - articles/ai-studio/*
              - includesModifiedFiles:
                  files:   
                    - articles/ai-services/*
              - includesModifiedFiles:
                  files:   
                    - articles/genomics/*
              - includesModifiedFiles:
                  files:   
                    - articles/open-datasets/*
              - includesModifiedFiles:
                  files:   
                    - articles/search/*
              - includesModifiedFiles:
                  files:   
                    - articles/azure-monitor/*
              - includesModifiedFiles:
                  files:  
                    - articles/advisor/*
              - includesModifiedFiles:
                  files:   
                    - articles/chaos-studio/*
              - includesModifiedFiles:
                  files:  
                    - articles/service-health/*
              - includesModifiedFiles:
                  files:  
                    - articles/azure-arc/*
              - includesModifiedFiles:
                  files:   
                    - articles/azure-linux/*
              - includesModifiedFiles:
                  files:   
                    - articles/azure-portal/*
              - includesModifiedFiles:
                  files:   
                    - articles/copilot/*
              - includesModifiedFiles:
                  files:   
                    - articles/lighthouse/*
              - includesModifiedFiles:
                  files:  
                    - articles/quotas/*
              - includesModifiedFiles:
                  files:   
                    - articles/container-registry/*
              - includesModifiedFiles:
                  files:  
                    - articles/kubernetes-fleet/*
        then:
          - addReply:
              reply: >-
                @${issueAuthor} - You tried to add content to a folder path that has been removed from this repository. Your pull request will be automatically closed. Submit your changes to the updated repository, which can be identified by clicking the Edit this Document link at the top of any published article for that product or service. 
          - if:
              - or:
                  - activitySenderHasPermission:
                      permission: None
                  - activitySenderHasPermission:
                      permission: Read
                  - activitySenderHasPermission:
                      permission: Write
                  - activitySenderHasPermission:
                      permission: Triage
                  - activitySenderHasPermission:
                      permission: Maintain
                  - activitySenderHasPermission:
                      permission: Admin
            then:
              - closePullRequest
